### PR TITLE
#AV-78192 Added terraform module to deploy vm on vmware cloud

### PR DESCRIPTION
**Pull request by Rohan-sss1**

### CODE REVIEW

**Comment by grastogi23** [comment]
This doesn't have information on cluster creation.

**Comment by Rohan-sss1** [comment]
Updated the Terraform module to configure VM's and create the cluster

**Comment by grastogi23** [comment]
why not commit to the terraform repo as well?

**Comment by Rohan-sss1** [comment]
It is a terraform module so we can put it in a separate repo, and the user can source it from Github link, for now, cd told me to add it in this repo

**Pull request merged**
